### PR TITLE
DOCS: update package dependencies

### PR DESCRIPTION
**Pull request by haydenrob**

### CODE REVIEW

**Comment by andyfaff** [comment]
Please don't create a readthedocs account just yet, we'll do that at a later stage.

**Comment by andyfaff** [comment]
You don't need to close this PR, it's just that it's not yet time to create an account on RTD. I've got no problems with merging it.
Also, I advise making PRs from feature branches, not master. When you work on larger scale projects making the PR from master creates issues.

**Comment by haydenrob** [comment]
Just saw this - I setup RTD earlier this morning. Can change it to your preference though, I can't make webhooks.

**Comment by andyfaff** [comment]
Ok, it's doesn't matter much I guess. Can you make me a maintainer on RTD?

**Comment by haydenrob** [comment]
Done

**Pull request merged**
