### PR TITLE
Improve RI

### PR DESCRIPTION
**Pull request by andyfaff**

### CODE REVIEW

**Comment by andyfaff** [comment]
@igresh @haydenrob I think this looks a lot cleaner now. ReflectModelSE takes an array of wavelengths and AOI, and marshals everything. 
Let me know what you think.

**Comment by andyfaff** [comment]
Now with fixed up getting_started notebook.

**Comment by haydenrob** [comment]
@andyfaff this is great! I'll have a look at fixing up other notebooks/tools.

**Comment by andyfaff** [comment]
BIG MERGE HERE, ALL EXISTING SCRIPTS WILL PROBABLY BREAK!

**Pull request merged**
